[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
libraries = []
cache = true
cache_path = "cache"
broadcast = "broadcast"
allow_paths = []
include_paths = []
force = true
evm_version = "london"
gas_reports = ["*"]
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 999999
verbosity = 0
ignored_error_codes = [
    "license",
    "code-size",
]
deny_warnings = false
build_info = true
build_info_path = 'out/build-info'
sparse_mode = false
ffi = true
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
tx_origin = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
initial_balance = "0xffffffffffffffffffffffff"
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = "0x0000000000000000000000000000000000000000"
block_timestamp = 1
block_difficulty = 0
block_prevrandao = "0x0000000000000000000000000000000000000000000000000000000000000000"
memory_limit = 33554432
extra_output = ["devdoc", "userdoc", "metadata", "storageLayout"]
extra_output_files = []
names = false
sizes = false
via_ir = false
no_storage_caching = false
no_rpc_rate_limit = false
bytecode_hash = "none"
cbor_metadata = true

fs_permissions = [
  { "access" = "read-write", "path" = "./script/output/"},
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/input/"},
  { "access" = "read", "path" = "./broadcast/" },
  { "access" = "read", "path" = "./out/" },
]

[profile.default.rpc_storage_caching]
chains = "all"
endpoints = "all"

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"

[etherscan]
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
arbitrum-sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
pangolin = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
crab = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://crab.api.subscan.io/api/scan/evm/contract/verifysource" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = []
contract_new_lines = false

[doc]
out = "docs"
title = "ORMP"
book = "book.toml"
homepage = "README.md"
ignore = []

[fuzz]
runs = 256
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
max_fuzz_dictionary_addresses = 15728640
max_fuzz_dictionary_values = 6553600
shrink_sequence = true

